/**
 * localization.js — ClassBridge i18n Module
 * Provides: translations object, t(), changeLanguage(), updateTranslations()
 * updateGlobalLanguageControlVisibility(), ensureGlobalLanguageControl()
 */
// --- LOCALIZATION & ACCESSIBILITY (FR-17, FR-16) ---
window.translations = window.translations || {
    en: {
        login_welcome: "Welcome to Noble Nexus",
        login_subtitle: "Sign in to Class Bridge",
        label_username: "Email",
        label_password: "Password",
        link_forgot_password: "Forgot Password?",
        btn_signin: "Sign In",
        btn_signin_microsoft: "Sign in with Microsoft",
        text_or: "OR",
        text_new_user: "New User?",
        link_signup: "Sign Up",
        link_help: "Need help? Contact support",
        msg_enter_credentials: "Please enter both username and password.",
        msg_checking: "Checking credentials...",
        msg_welcome: "Welcome, {user_id}",
        msg_login_failed: "Login failed",
        msg_network_error: "Network Error: {error}. Is the backend running?",
        msg_google_verify: "Verifying Google Token...",
        msg_microsoft_conn: "Connecting to Microsoft...",
        msg_microsoft_verify: "Verifying Microsoft Token...",
        // Sidebar & Dashboard
        sidebar_dashboard: "Dashboard",
        sidebar_my_courses: "My Courses",
        sidebar_course_list: "Course List",
        sidebar_assignments: "Assignments",
        sidebar_exams: "Exams",
        sidebar_upcoming_exams: "Upcoming Exams",
        sidebar_results: "Results",
        sidebar_profile: "Profile",
        sidebar_view_profile: "View Profile",
        sidebar_settings: "Settings",
        sidebar_communication: "Communication",
        sidebar_lms: "Courses (LMS)",
        sidebar_ai_assistant: "AI Assistant",
        sidebar_timetable: "Timetable",
        sidebar_view_timetable: "View timetable",
        sidebar_attendance: "Attendance",
        sidebar_take_attendance: "Take attendance",
        sidebar_attendance_sheet: "Attendance sheet",
        sidebar_monthly_report: "Monthly report",
        sidebar_approve_leave: "Approve/deny leave",
        sidebar_apply_leave: "Apply for leave",
        sidebar_assignment_group: "Assignment",
        sidebar_create_assignment: "Create assignment",
        sidebar_view_submitted: "View submitted",
        sidebar_approve_reassign: "Approve / Reassign",
        sidebar_enter_marks: "Enter & Update Marks",
        sidebar_online_test: "Online Test",
        sidebar_question_bank: "Question Bank",
        sidebar_create_test: "Create & Edit Tests",
        sidebar_assign_max_marks: "Assign Max Marks",
        sidebar_view_test_results: "View Results",
        sidebar_progress_card: "Progress Card",
        sidebar_enter_progress: "Enter Progress Marks",
        sidebar_save_publish: "Save & Publish Marks",
        sidebar_view_progress: "View Progress Card",
        sidebar_pay_slips: "Pay Slips",
        sidebar_view_payslips: "View Payslips",
        sidebar_students: "Students",
        sidebar_add_student: "Add Student",
        sidebar_student_list: "Student List",
        sidebar_reports: "Reports",
        sidebar_attendance_report: "Attendance Report",
        sidebar_performance_report: "Performance Report",
        sidebar_resource_library: "Resource Library",
        sidebar_ai_copilot: "AI Co-Pilot",
        sidebar_roles_perms: "Roles & Perms",
        sidebar_staff_faculty: "Staff & Faculty",
        sidebar_system_settings: "System Settings",
        sidebar_academic_progress: "Academic Progress",
        sidebar_fees_payments: "Fees & Payments",
        sidebar_education_assistant: "Education Assistant",
        // Student Dashboard
        student_dashboard_title: "Student Dashboard",
        btn_log_activity: "Log Activity",
        student_live_class: "🔴 Live Class in Progress!",
        btn_join_class: "Join Class",
        btn_join_whiteboard: "Join Whiteboard",
        student_key_metrics: "Student Key Metrics",
        student_upcoming_live: "Upcoming Live Classes",
        msg_no_live_classes: "No live classes scheduled.",
        live_class_session: "LIVE CLASS IN SESSION",
        btn_join_now: "JOIN NOW",
        student_level: "Level",
        student_my_courses: "My Courses",
        msg_no_courses: "You are not enrolled in any courses yet.",
        student_upcoming_assignments: "Upcoming Assignments & Projects",
        msg_loading_assignments: "Loading assignments...",
        tab_progress_graph: "📈 Progress Graph",
        tab_activity_history: "📜 Activity History",
        // Parent Portal
        parent_portal_title: "Parent Portal",
        label_select_child: "Select Your Child",
        ph_child_id: "Enter Child's Student ID (e.g., S001)",
        btn_view_progress: "View Progress",
        msg_enter_child_id: "Enter the Student ID provided by the school.",
        parent_overview_for: "Overview for",
        parent_key_updates: "Key Updates",
        update_school_close: "School closes early tomorrow at 2 PM.",
        update_report_cards: "Report cards have been published.",
        parent_academic_progress: "Academic Progress",
        parent_teacher_feedback: "Teacher Feedback",
        msg_loading_feedback: "Loading feedback...",
        parent_recent_marks: "Recent Marks",
        th_subject: "Subject",
        th_exam: "Exam",
        th_score: "Score",
        parent_performance_chart: "Performance Chart",
        parent_report_cards: "Report Cards",
        term_1_report: "Term 1 Report",
        badge_download: "Download",
        // Modals - Roles
        modal_select_role: "Select Role",
        role_principal: "Principal",
        role_super_admin: "Super Admin",
        // Modals - Upload Resource
        modal_upload_resource: "Upload Resource",
        label_res_title: "Title",
        label_res_category: "Category",
        opt_school_policy: "School Policy",
        opt_exam_schedule: "Exam Schedule",
        opt_form: "Leave/Admin Form",
        opt_other: "Other",
        label_res_desc: "Description",
        label_res_file: "File (PDF, Doc)",
        text_max_size: "Max size 5MB",
        // Modals - Permission Edit
        modal_edit_permission: "Edit Permission",
        label_perm_code: "Permission Code",
        label_perm_title: "Permission Title",
        btn_cancel: "Cancel",
        btn_update: "Update",
        // Modals - Take Quiz
        modal_take_quiz: "Quiz",
        btn_submit_quiz: "Submit Quiz",
        // Modals - Add Student
        modal_add_student: "➕ Add New Student",
        label_student_id: "Student ID",
        label_full_name: "Full Name",
        label_default_password: "Default Password",
        label_grade: "Grade",
        // Modals - Access Card
        modal_access_card: "Student Access Card",
        label_topic: "Topic",
        ph_topic: "e.g. Photosynthesis",
        // label_grade: "Grade", // Duplicated
        label_subject: "Subject",
        label_duration: "Duration (Minutes)",
        label_instructions: "Additional Instructions / Context",
        ph_instructions: "e.g. Focus on vocabulary, include a group activity...",
        label_upload_pdf: "Upload PDF Context (Optional)",
        btn_generate_plan: "Generate Lesson Plan",
        // Modals - Quiz
        modal_ai_quiz: "AI Quiz Generator",
        label_questions_count: "Questions",
        btn_generate_quiz: "Generate Quiz",
        // Modals - Schedule Class
        modal_schedule_class: "📅 Schedule Live Class",
        label_date_time: "Date & Time",
        label_target_students: "Target Students",
        label_filter_group: "Filter by Group",
        opt_all_students: "-- All Students --",
        label_select_all: "Select All",
        label_meet_link: "Google Meet Link",
        ph_meet_link_long: "https://meet.google.com/...",
        help_meet_link: "Copy paste a link from Google Meet or Zoom.",
        btn_schedule: "Schedule",
        // Dashboard Metrics & Content
        dashboard_students: "Students",
        dashboard_teachers: "Teachers",
        dashboard_staff: "Staff",
        dashboard_awards: "Awards",
        metric_change_teachers: "! 3% from last month",
        metric_change_staff: "→ No change",
        metric_change_awards: "↑ 15% from last month",
        btn_schedule_class: "Schedule Class",
        btn_ai_quiz: "AI Quiz",
        btn_plan_lesson: "Plan Lesson",
        btn_whiteboard: "Whiteboard",
        btn_export: "Export",
        btn_engagement_helper: "Engagement Helper",
        // Assignments & Payslips
        asg_active_title: "Active Assignments",
        asg_active_subtitle: "Create, review submissions, and track progress by class.",
        btn_create_assignment: "Create Assignment",
        asg_review_title: "Review Queue",
        btn_refresh: "Refresh",
        msg_loading_submissions: "Loading submissions...",
        msg_failed_load_submissions: "Failed to load submissions.",
        asg_review_empty: "All caught up! No submissions pending review.",
        marks_entry_title: "Marks Entry",
        marks_select_assignment: "Select Assignment",
        marks_load_submissions: "Load Submissions",
        marks_select_prompt: "Select an assignment to view submissions.",
        msg_no_assignments: "No assignments yet.",
        msg_failed_load_assignments: "Failed to load assignments.",
        msg_assignment_requires_backend: "Assignments require the backend. Open http://127.0.0.1:8000.",
        msg_fill_assignment_fields: "Please fill in Title, Due Date, and Class (Grade).",
        msg_create_assignment_failed: "Failed to create assignment.",
        msg_create_assignment_network_error: "Network error creating assignment.",
        msg_assignment_submit_required: "Please write something or provide a link.",
        msg_assignment_submit_success: "Submitted successfully!",
        msg_assignment_submit_failed: "Check submission failed.",
        msg_assignment_submit_network_error: "Network error.",
        btn_view_submissions: "View Submissions",
        label_status: "Status",
        status_submitted: "Submitted",
        label_feedback: "Feedback",
        btn_save: "Save",
        btn_reassign: "Reassign",
        asg_modal_title: "📝 New Assignment",
        label_title: "Title",
        label_description: "Description",
        label_class_grade: "Class (Grade)",
        label_select_grade: "Select Grade",
        label_points: "Points",
        label_section: "Section",
        label_select_section_optional: "Select Section (optional)",
        label_due_date: "Due Date",
        btn_create: "Create",
        payslip_title: "My Payslips",
        payslip_ytd: "Year-To-Date",
        payslip_net_pay_label: "Net Pay",
        payslip_latest: "Latest Pay Period",
        payslip_latest_sub: "Net Pay • Sep 2024",
        payslip_payment_method: "Payment Method",
        payslip_account_masked: "Account •••• 2391",
        payslip_recent: "Recent Payslips",
        payslip_download_all: "Download All",
        payslip_processed_paid: "Processed: Oct 01, 2024 • Status: Paid",
        payslip_view_details: "View Details",
        payslip_gross: "Gross: $5,000",
        payslip_deductions: "Deductions: $880",
        payslip_taxes: "Taxes: $620",
        payslip_print_title: "Print Payslips",
        payslip_generate_pdf: "Generate Payslip PDF",
        payslip_pay_period: "Pay Period",
        payslip_delivery: "Delivery",
        payslip_download_pdf: "Download PDF",
        payslip_email_me: "Email to me",
        payslip_generate_btn: "Generate PDF",
        payslip_preview: "Payslip Preview",
        payslip_employee_id: "Employee ID: T-1024",
        payslip_processed_date: "Processed: Oct 01, 2024",
        payslip_earnings: "Earnings",
        payslip_base_salary: "Base Salary",
        payslip_allowance: "Allowance",
        payslip_deduction_label: "Deductions",
        payslip_tax: "Tax",
        payslip_insurance: "Insurance",
        pay_advance_title: "Apply for Pay Advance",
        pay_advance_amount: "Amount Required",
        pay_advance_reason: "Reason",
        pay_advance_repayment: "Preferred Repayment",
        pay_advance_next_period: "Next Pay Period",
        pay_advance_two_periods: "Two Pay Periods",
        pay_advance_submit: "Submit Request",
        pay_advance_recent: "Recent Requests",
        pay_advance_label: "Advance",
        pay_advance_submitted: "Submitted: Aug 12, 2024",
        pay_advance_pending: "Pending",
        pay_advance_approved: "Approved",
        dashboard_live_controls: "Live Class Controls",
        dashboard_now: "Now",
        ph_meet_link: "Google Meet Link",
        btn_start: "Start",
        btn_end: "End",
        dashboard_calendar: "Calendar",
        dashboard_upcoming_events: "Upcoming events",
        dashboard_performance_dist: "Performance Distribution",
        dashboard_class_avg_score: "Class Average Activity Score",
        // Headers
        header_messages: "Messages",
        header_notifications: "Notifications",
        header_my_profile: "My Profile",
        header_logout: "Logout",
        ph_search: "Search here...",
        // New Added Keys
        header_view_all_messages: "View All Messages",
        header_mark_read: "Mark all as read",
        notif_sys_maint: "System Maintenance",
        notif_sys_maint_desc: "Scheduled for tonight at 12 AM.",
        notif_assign_sub: "Assignment Submitted",
        notif_assign_sub_desc: "Alice Smith submitted \"Math HW\".",
        login_journey_title: "Your Learning Journey Continues",
        login_journey_desc: "Log in to access your courses, live classes, and personalized AI insights.",
        stat_pass_rate: "Pass Rate",
        stat_access: "Access",
        stat_students: "Students",
        footer_company: "Company",
        footer_about: "About us",
        footer_press: "Press",
        footer_careers: "Careers",
        footer_engineering: "Engineering",
        footer_accessibility: "Accessibility",
        footer_resources: "Resources",
        footer_big_ideas: "Big Ideas",
        footer_training: "Training",
        footer_remote_learning: "Remote Learning",
        footer_support: "Support",
        footer_help_center: "Help Center",
        footer_contact: "Contact",
        footer_privacy: "Privacy Center",
        footer_cookies: "Cookie Settings",
        footer_get_app: "Get the App",
        footer_terms: "Terms",
        text_scan_visit: "Scan to visit",
        text_product_by: "a product by Noble Nexus",
        text_a_product_by: "A Product By",
        footer_noble_nexus_plus: "Noble Nexus Plus",
        // Landing Page Mock Data
        feat_why_title: "Why Noble Nexus?",
        feat_main_title: "Everything you need to excel",
        feat_analytics_title: "Smart Analytics",
        feat_analytics_desc: "Track academic performance trends with clear, AI-driven visualizations that help students improve faster.",
        feat_live_title: "Live Classrooms",
        feat_live_desc: "Integrated video conferencing allows for seamless remote learning sessions directly from your dashboard.",
        feat_ai_title: "AI Guidance",
        feat_ai_desc: "Experience personalized learning paths and automated feedback designed for every student's unique journey.",
        about_title: "About ClassBridge",
        about_main_title: "Empowering the Future of Education",
        about_desc: "ClassBridge is designed to close the gap between traditional schooling and modern technology. We provide a unified ecosystem where learning meets innovation:",
        about_teachers: "For Teachers",
        about_teachers_desc: "Manage classrooms effortlessly with AI-powered attendance, automated grading, and smart lesson planning tools.",
        about_students: "For Students",
        about_students_desc: "Access personalized learning paths, track real-time progress, and stay engaged with gamified education goals.",
        about_parents: "For Parents",
        about_parents_desc: "Stay informed with instant updates on attendance, academic performance, and school events.",
        btn_discover_more: "Discover More",
        stat_engagement: "Engagement Rate",
        stat_ai_support: "AI Support",
        stat_active_students: "Active Students",
        nav_teachers: "Teachers",
        nav_students: "Students",
        nav_schools: "Schools",
        nav_resources: "Resources",
        btn_log_in: "Log in",
        text_back: "Back",
        login_not_a: "Not a",
        login_switch_role: "Switch Role",
        login_student_login: "Student Login",
        login_teacher_portal: "Teacher Portal",
        login_parent_access: "Parent Access",
        login_principal_login: "Principal Login",
        login_super_admin: "Super Admin",
        login_root_admin_portal: "Root Admin Portal",
        login_generic: "Login",
        role_student: "Student",
        role_teacher: "Teacher",
        role_parent: "Parent",
        role_others: "Others",
        role_admin: "Admin",
        role_root_admin: "Root Admin",
        hero_heading: "Where classrooms\nbecome communities",
        hero_subtitle: "Empowering educational institutions through innovative solutions",
        hero_get_started_as: "Get started as a...",
        feat_modern_title: "Built for the Modern Classroom",
        feat_quiz_gen: "Quiz Generator",
        feat_quiz_desc: "Upload a PDF chapter, and our AI generates 20 distinct questions with answer keys in seconds.",
        link_try_generator: "Try Generator →",
        feat_student_insights: "Student Insights",
        feat_student_insights_desc: "Beyond grades. See who is trying hard but struggling, and who needs more challenging material.",
        link_view_report: "View Sample Report →",
        feat_hybrid: "Hybrid Classroom",
        feat_hybrid_desc: "Seamlessly switch between in-person and remote teaching with built-in video logic.",
        link_see_how: "See How →",
        cta_ready_transform: "Ready to transform your teaching?",
        btn_join_free: "Join Noble Nexus for Free"
    },
    es: {
        login_welcome: "Bienvenido a Noble Nexus",
        login_subtitle: "Inicia sesión en el portal Noble Nexus",
        label_username: "Usuario / ID de Estudiante",
        label_password: "Contraseña",
        link_forgot_password: "¿Olvidaste tu contraseña?",
        btn_signin: "Iniciar Sesión",
        btn_signin_microsoft: "Entrar con Microsoft",
        text_or: "O",
        text_new_user: "¿Nuevo usuario?",
        link_signup: "Regístrate",
        link_help: "¿Necesitas ayuda? Contacta soporte",
        msg_enter_credentials: "Por favor ingrese usuario y contraseña.",
        msg_checking: "Verificando credenciales...",
        msg_welcome: "Bienvenido, {user_id}",
        msg_login_failed: "Inicio de sesión fallido",
        msg_network_error: "Error de red: {error}. ¿Está el servidor activo?",
        msg_google_verify: "Verificando token de Google...",
        msg_microsoft_conn: "Conectando con Microsoft...",
        msg_microsoft_verify: "Verificando token de Microsoft...",
        // Sidebar & Dashboard
        sidebar_dashboard: "Panel de Control",
        sidebar_my_courses: "Mis Cursos",
        sidebar_course_list: "Lista de Cursos",
        sidebar_assignments: "Tareas",
        sidebar_exams: "Exámenes",
        sidebar_upcoming_exams: "Próximos Exámenes",
        sidebar_results: "Resultados",
        sidebar_profile: "Perfil",
        sidebar_view_profile: "Ver Perfil",
        sidebar_settings: "Ajustes",
        sidebar_communication: "Comunicación",
        sidebar_lms: "Cursos (LMS)",
        sidebar_ai_assistant: "Asistente IA",
        sidebar_timetable: "Horario",
        sidebar_view_timetable: "Ver Horario",
        sidebar_attendance: "Asistencia",
        sidebar_take_attendance: "Tomar Asistencia",
        sidebar_attendance_sheet: "Hoja de Asistencia",
        sidebar_monthly_report: "Informe Mensual",
        sidebar_approve_leave: "Aprobar/Rechazar Permiso",
        sidebar_apply_leave: "Solicitar Permiso",
        sidebar_assignment_group: "Asignación",
        sidebar_create_assignment: "Crear Tarea",
        sidebar_view_submitted: "Ver Entregas",
        sidebar_approve_reassign: "Aprobar / Reasignar",
        sidebar_enter_marks: "Ingresar Notas",
        sidebar_online_test: "Prueba en Línea",
        sidebar_question_bank: "Banco de Preguntas",
        sidebar_create_test: "Crear/Editar Pruebas",
        sidebar_assign_max_marks: "Asignar Notas Máx.",
        sidebar_view_test_results: "Ver Resultados",
        sidebar_progress_card: "Boletín",
        sidebar_enter_progress: "Ingresar Progresos",
        sidebar_save_publish: "Guardar y Publicar",
        sidebar_view_progress: "Ver Boletín",
        sidebar_pay_slips: "Nóminas",
        sidebar_view_payslips: "Ver Nóminas",
        sidebar_students: "Estudiantes",
        sidebar_add_student: "Agregar Estudiante",
        sidebar_student_list: "Lista de Estudiantes",
        sidebar_reports: "Informes",
        sidebar_attendance_report: "Informe de Asistencia",
        sidebar_performance_report: "Informe de Rendimiento",
        sidebar_resource_library: "Biblioteca de Recursos",
        sidebar_ai_copilot: "Copiloto IA",
        sidebar_roles_perms: "Roles y Permisos",
        sidebar_staff_faculty: "Personal y Facultad",
        sidebar_system_settings: "Configuración del Sistema",
        sidebar_academic_progress: "Progreso Académico",
        sidebar_fees_payments: "Pagos y Tarifas",
        sidebar_education_assistant: "Asistente Educativo",
        // Student Dashboard
        student_dashboard_title: "Panel de Estudiante",
        btn_log_activity: "Registrar Actividad",
        student_live_class: "🔴 ¡Clase en Vivo en Progreso!",
        btn_join_class: "Unirse a Clase",
        btn_join_whiteboard: "Unirse a Pizarra",
        student_key_metrics: "Métricas Clave del Estudiante",
        student_upcoming_live: "Próximas Clases en Vivo",
        msg_no_live_classes: "No hay clases en vivo programadas.",
        live_class_session: "CLASE EN VIVO EN SESIÓN",
        btn_join_now: "UNIRSE AHORA",
        student_level: "Nivel",
        student_my_courses: "Mis Cursos",
        msg_no_courses: "Aún no estás inscrito en ningún curso.",
        student_upcoming_assignments: "Próximas Tareas y Proyectos",
        msg_loading_assignments: "Cargando tareas...",
        tab_progress_graph: "📈 Gráfico de Progreso",
        tab_activity_history: "📜 Historial de Actividad",
        // Parent Portal
        parent_portal_title: "Portal de Padres",
        label_select_child: "Seleccione a su Hijo",
        ph_child_id: "Ingrese el ID de estudiante (ej. S001)",
        btn_view_progress: "Ver Progreso",
        msg_enter_child_id: "Ingrese el ID de estudiante proporcionado por la escuela.",
        parent_overview_for: "Resumen para",
        parent_key_updates: "Actualizaciones Clave",
        update_school_close: "La escuela cierra temprano mañana a las 2 PM.",
        update_report_cards: "Se han publicado las boletas de calificaciones.",
        parent_academic_progress: "Progreso Académico",
        parent_teacher_feedback: "Comentarios del Profesor",
        msg_loading_feedback: "Cargando comentarios...",
        parent_recent_marks: "Calificaciones Recientes",
        th_subject: "Asignatura",
        th_exam: "Examen",
        th_score: "Calificación",
        parent_performance_chart: "Gráfico de Rendimiento",
        parent_report_cards: "Boletas de Calificaciones",
        term_1_report: "Boleta Trimestre 1",
        badge_download: "Descargar",
        // Modals - Roles
        modal_select_role: "Seleccionar Rol",
        role_principal: "Director",
        role_super_admin: "Super Administrador",
        // Modals - Upload Resource
        modal_upload_resource: "Subir Recurso",
        label_res_title: "Título",
        label_res_category: "Categoría",
        opt_school_policy: "Política Escolar",
        opt_exam_schedule: "Horario de Exámenes",
        opt_form: "Formulario de Permiso/Admin",
        opt_other: "Otro",
        label_res_desc: "Descripción",
        label_res_file: "Archivo (PDF, Doc)",
        text_max_size: "Tamaño máx 5MB",
        // Modals - Permission Edit
        modal_edit_permission: "Editar Permiso",
        label_perm_code: "Código de Permiso",
        label_perm_title: "Título de Permiso",
        btn_cancel: "Cancelar",
        btn_update: "Actualizar",
        // Modals - Take Quiz
        modal_take_quiz: "Prueba",
        btn_submit_quiz: "Enviar Prueba",
        // Modals - Add Student
        modal_add_student: "➕ Añadir Nuevo Estudiante",
        label_student_id: "ID de Estudiante",
        label_full_name: "Nombre Completo",
        label_default_password: "Contraseña Predeterminada",
        label_grade: "Grado",
        // Modals - Access Card
        modal_access_card: "Tarjeta de Acceso Estudiantil",
        label_topic: "Tema",
        ph_topic: "ej. Fotosíntesis",
        // label_grade: "Grado", // Duplicated
        label_subject: "Asignatura",
        label_duration: "Duración (Minutos)",
        label_instructions: "Instrucciones Adicionales / Contexto",
        ph_instructions: "ej. Enfocarse en vocabulario...",
        label_upload_pdf: "Subir PDF de Contexto (Opcional)",
        btn_generate_plan: "Generar Plan",
        // Modals - Quiz
        modal_ai_quiz: "Generador de Pruebas IA",
        label_questions_count: "Preguntas",
        btn_generate_quiz: "Generar Prueba",
        // Modals - Schedule Class
        modal_schedule_class: "📅 Programar Clase en Vivo",
        label_date_time: "Fecha y Hora",
        label_target_students: "Estudiantes Objetivo",
        label_filter_group: "Filtrar por Grupo",
        opt_all_students: "-- Todos los Estudiantes --",
        label_select_all: "Seleccionar Todos",
        label_meet_link: "Enlace de Google Meet",
        ph_meet_link_long: "https://meet.google.com/...",
        help_meet_link: "Copie y pegue un enlace de Google Meet o Zoom.",
        btn_schedule: "Programar",
        // Dashboard Metrics & Content
        dashboard_students: "Estudiantes",
        dashboard_teachers: "Profesores",
        dashboard_staff: "Personal",
        dashboard_awards: "Premios",
        metric_change_teachers: "! 3% del mes pasado",
        metric_change_staff: "→ Sin cambios",
        metric_change_awards: "↑ 15% del mes pasado",
        btn_schedule_class: "Programar Clase",
        btn_ai_quiz: "Prueba IA",
        btn_plan_lesson: "Planificar Lección",
        btn_whiteboard: "Pizarra",
        btn_export: "Exportar",
        btn_engagement_helper: "Ayudante de Compromiso",
        // Assignments & Payslips
        asg_active_title: "Asignaciones activas",
        asg_active_subtitle: "Crea, revisa entregas y sigue el progreso por clase.",
        btn_create_assignment: "Crear asignación",
        asg_review_title: "Cola de revisión",
        btn_refresh: "Actualizar",
        msg_loading_submissions: "Cargando entregas...",
        msg_failed_load_submissions: "No se pudieron cargar las entregas.",
        asg_review_empty: "¡Todo al día! No hay entregas pendientes.",
        marks_entry_title: "Registro de calificaciones",
        marks_select_assignment: "Seleccionar asignación",
        marks_load_submissions: "Cargar entregas",
        marks_select_prompt: "Selecciona una asignación para ver entregas.",
        msg_no_assignments: "Aún no hay asignaciones.",
        msg_failed_load_assignments: "No se pudieron cargar las asignaciones.",
        msg_assignment_requires_backend: "Las asignaciones requieren el backend. Abre http://127.0.0.1:8000.",
        msg_fill_assignment_fields: "Por favor completa Título, Fecha de entrega y Clase (Grado).",
        msg_create_assignment_failed: "No se pudo crear la asignación.",
        msg_create_assignment_network_error: "Error de red al crear la asignación.",
        msg_assignment_submit_required: "Escribe algo o proporciona un enlace.",
        msg_assignment_submit_success: "¡Enviado con éxito!",
        msg_assignment_submit_failed: "Falló el envío.",
        msg_assignment_submit_network_error: "Error de red.",
        btn_view_submissions: "Ver entregas",
        label_status: "Estado",
        status_submitted: "Enviado",
        label_feedback: "Comentario",
        btn_save: "Guardar",
        btn_reassign: "Reasignar",
        asg_modal_title: "📝 Nueva asignación",
        label_title: "Título",
        label_description: "Descripción",
        label_class_grade: "Clase (Grado)",
        label_select_grade: "Seleccionar grado",
        label_points: "Puntos",
        label_section: "Sección",
        label_select_section_optional: "Seleccionar sección (opcional)",
        label_due_date: "Fecha de entrega",
        btn_create: "Crear",
        payslip_title: "Mis nóminas",
        payslip_ytd: "Acumulado del año",
        payslip_net_pay_label: "Pago neto",
        payslip_latest: "Último periodo de pago",
        payslip_latest_sub: "Pago neto • Sep 2024",
        payslip_payment_method: "Método de pago",
        payslip_account_masked: "Cuenta •••• 2391",
        payslip_recent: "Nóminas recientes",
        payslip_download_all: "Descargar todo",
        payslip_processed_paid: "Procesado: Oct 01, 2024 • Estado: Pagado",
        payslip_view_details: "Ver detalles",
        payslip_gross: "Bruto: $5,000",
        payslip_deductions: "Deducciones: $880",
        payslip_taxes: "Impuestos: $620",
        payslip_print_title: "Imprimir nóminas",
        payslip_generate_pdf: "Generar PDF de nómina",
        payslip_pay_period: "Periodo de pago",
        payslip_delivery: "Entrega",
        payslip_download_pdf: "Descargar PDF",
        payslip_email_me: "Enviarme por correo",
        payslip_generate_btn: "Generar PDF",
        payslip_preview: "Vista previa de nómina",
        payslip_employee_id: "ID de empleado: T-1024",
        payslip_processed_date: "Procesado: Oct 01, 2024",
        payslip_earnings: "Ingresos",
        payslip_base_salary: "Salario base",
        payslip_allowance: "Asignación",
        payslip_deduction_label: "Deducciones",
        payslip_tax: "Impuesto",
        payslip_insurance: "Seguro",
        pay_advance_title: "Solicitar anticipo de pago",
        pay_advance_amount: "Monto requerido",
        pay_advance_reason: "Motivo",
        pay_advance_repayment: "Reembolso preferido",
        pay_advance_next_period: "Próximo periodo de pago",
        pay_advance_two_periods: "Dos periodos de pago",
        pay_advance_submit: "Enviar solicitud",
        pay_advance_recent: "Solicitudes recientes",
        pay_advance_label: "Anticipo",
        pay_advance_submitted: "Enviado: Aug 12, 2024",
        pay_advance_pending: "Pendiente",
        pay_advance_approved: "Aprobado",
        dashboard_live_controls: "Controles de Clase en Vivo",
        dashboard_now: "Ahora",
        ph_meet_link: "Enlace de Google Meet",
        btn_start: "Comenzar",
        btn_end: "Terminar",
        dashboard_calendar: "Calendario",
        dashboard_upcoming_events: "Próximos eventos",
        dashboard_performance_dist: "Distribución de Rendimiento",
        dashboard_class_avg_score: "Puntaje Promedio de Actividad",
        // Headers
        header_messages: "Mensajes",
        header_notifications: "Notificaciones",
        header_my_profile: "Mi Perfil",
        header_logout: "Cerrar Sesión",
        ph_search: "Buscar aquí...",
        stat_active_students: "Estudiantes activos",
        nav_teachers: "Profesores",
        nav_students: "Estudiantes",
        nav_schools: "Escuelas",
        nav_resources: "Recursos",
        btn_log_in: "Iniciar sesión",
        text_back: "Volver",
        login_not_a: "¿No eres",
        login_switch_role: "Cambiar rol",
        login_student_login: "Inicio de estudiante",
        login_teacher_portal: "Portal del profesor",
        login_parent_access: "Acceso para padres",
        login_principal_login: "Inicio de director",
        login_super_admin: "Súper administrador",
        login_root_admin_portal: "Portal de administrador raíz",
        login_generic: "Iniciar sesión",
        role_student: "Estudiante",
        role_teacher: "Profesor",
        role_parent: "Padre/Madre",
        role_others: "Otros",
        role_admin: "Administrador",
        role_root_admin: "Administrador raíz",
        hero_heading: "Donde las aulas\nse convierten en comunidades",
        hero_subtitle: "Impulsando instituciones educativas mediante soluciones innovadoras",
        hero_get_started_as: "Comenzar como...",
        feat_why_title: "¿Por qué Noble Nexus?",
        feat_main_title: "Todo lo que necesitas para destacar",
        feat_analytics_title: "Analítica inteligente",
        feat_analytics_desc: "Sigue tendencias de rendimiento académico con visualizaciones claras impulsadas por IA que ayudan a mejorar más rápido.",
        feat_live_title: "Aulas en vivo",
        feat_live_desc: "La videoconferencia integrada permite clases remotas fluidas directamente desde tu panel.",
        feat_ai_title: "Guía con IA",
        feat_ai_desc: "Disfruta rutas de aprendizaje personalizadas y retroalimentación automática para cada estudiante.",
        about_title: "Sobre ClassBridge",
        about_main_title: "Impulsando el futuro de la educación",
        about_desc: "ClassBridge está diseñado para cerrar la brecha entre la escuela tradicional y la tecnología moderna.",
        about_teachers: "Para docentes",
        about_teachers_desc: "Gestiona clases fácilmente con asistencia con IA, calificación automática y planeación inteligente.",
        about_students: "Para estudiantes",
        about_students_desc: "Accede a rutas personalizadas, sigue tu progreso en tiempo real y mantente motivado.",
        about_parents: "Para familias",
        about_parents_desc: "Mantente al día con asistencia, rendimiento académico y eventos escolares.",
        btn_discover_more: "Descubrir más",
        stat_engagement: "Tasa de participación",
        stat_ai_support: "Soporte de IA",
        footer_company: "Empresa",
        footer_about: "Sobre nosotros",
        footer_press: "Prensa",
        footer_careers: "Carreras",
        footer_engineering: "Ingeniería",
        footer_accessibility: "Accesibilidad",
        footer_resources: "Recursos",
        footer_big_ideas: "Grandes ideas",
        footer_training: "Capacitación",
        footer_remote_learning: "Aprendizaje remoto",
        footer_support: "Soporte",
        footer_help_center: "Centro de ayuda",
        footer_contact: "Contacto",
        footer_privacy: "Centro de privacidad",
        footer_cookies: "Configuración de cookies",
        footer_get_app: "Obtén la app",
        footer_terms: "Términos",
        text_scan_visit: "Escanea para visitar",
        text_product_by: "un producto de Noble Nexus",
        text_a_product_by: "Un producto de",
        footer_noble_nexus_plus: "Noble Nexus Plus",
        feat_modern_title: "Creado para el aula moderna",
        feat_quiz_gen: "Generador de cuestionarios",
        feat_quiz_desc: "Sube un PDF y la IA crea preguntas con respuestas en segundos.",
        link_try_generator: "Probar generador →",
        feat_student_insights: "Información del estudiante",
        feat_student_insights_desc: "Ve más allá de las notas y detecta necesidades de apoyo o reto.",
        link_view_report: "Ver informe de ejemplo →",
        feat_hybrid: "Aula híbrida",
        feat_hybrid_desc: "Alterna sin fricción entre enseñanza presencial y remota.",
        link_see_how: "Ver cómo →",
        cta_ready_transform: "¿Listo para transformar tu enseñanza?",
        btn_join_free: "Únete gratis a Noble Nexus"
    },
    ar: {
        login_welcome: "مرحباً بك في Noble Nexus",
        login_subtitle: "بوابة تسجيل الدخول إلى Noble Nexus",
        label_username: "اسم المستخدم / هوية الطالب",
        label_password: "كلمة المرور",
        link_forgot_password: "هل نسيت كلمة المرور؟",
        btn_signin: "تسجيل الدخول",
        btn_signin_microsoft: "تسجيل الدخول باستخدام Microsoft",
        text_or: "أو",
        text_new_user: "مستخدم جديد؟",
        link_signup: "سجل الآن",
        link_help: "تحتاج إلى مساعدة؟ اتصل بالدعم",
        msg_enter_credentials: "يرجى إدخال اسم المستخدم وكلمة المرور.",
        msg_checking: "جاري التحقق من بيانات الاعتماد...",
        msg_welcome: "مرحباً، {user_id}",
        msg_login_failed: "فشل تسجيل الدخول",
        msg_network_error: "خطأ في الشبكة: {error}. هل الخادم يعمل؟",
        msg_google_verify: "جارٍ التحقق من رمز Google...",
        msg_microsoft_conn: "جارٍ الاتصال بـ Microsoft...",
        msg_microsoft_verify: "جارٍ التحقق من رمز Microsoft...",
        // Sidebar & Dashboard
        sidebar_dashboard: "لوحة القيادة",
        sidebar_my_courses: "دوراتي",
        sidebar_course_list: "قائمة الدورات",
        sidebar_assignments: "الواجبات",
        sidebar_exams: "الامتحانات",
        sidebar_upcoming_exams: "الامتحانات القادمة",
        sidebar_results: "النتائج",
        sidebar_profile: "الملف الشخصي",
        sidebar_view_profile: "عرض الملف الشخصي",
        sidebar_settings: "الإعدادات",
        sidebar_communication: "التواصل",
        sidebar_lms: "الدورات (LMS)",
        sidebar_ai_assistant: "مساعد الذكاء الاصطناعي",
        sidebar_timetable: "الجدول الزمني",
        sidebar_view_timetable: "عرض الجدول",
        sidebar_attendance: "الحضور",
        sidebar_take_attendance: "تسجيل الحضور",
        sidebar_attendance_sheet: "ورقة الحضور",
        sidebar_monthly_report: "تقرير شهري",
        sidebar_approve_leave: "الموافقة على الإجازة",
        sidebar_apply_leave: "طلب إجازة",
        sidebar_assignment_group: "الواجب",
        sidebar_create_assignment: "إنشاء واجب جديد",
        sidebar_view_submitted: "عرض المقدمة",
        sidebar_approve_reassign: "موافق/إعادة تعيين",
        sidebar_enter_marks: "إدخال الدرجات",
        sidebar_online_test: "اختبار عبر الإنترنت",
        sidebar_question_bank: "بنك الأسئلة",
        sidebar_create_test: "إنشاء وتعديل الاختبارات",
        sidebar_assign_max_marks: "تعيين الدرجات القصوى",
        sidebar_view_test_results: "عرض النتائج",
        sidebar_progress_card: "بطاقة التقدم",
        sidebar_enter_progress: "إدخال درجات التقدم",
        sidebar_save_publish: "حفظ ونشر",
        sidebar_view_progress: "عرض البطاقة",
        sidebar_pay_slips: "قسائم الراتب",
        sidebar_view_payslips: "عرض القسائم",
        sidebar_students: "الطلاب",
        sidebar_add_student: "إضافة طالب",
        sidebar_student_list: "قائمة الطلاب",
        sidebar_reports: "التقارير",
        sidebar_attendance_report: "تقرير الحضور",
        sidebar_performance_report: "تقرير الأداء",
        sidebar_resource_library: "مكتبة الموارد",
        sidebar_ai_copilot: "مساعد الذكاء الاصطناعي",
        sidebar_roles_perms: "الأدوار والأذونات",
        sidebar_staff_faculty: "الموظفون",
        sidebar_system_settings: "إعدادات النظام",
        sidebar_academic_progress: "التقدم الأكاديمي",
        sidebar_fees_payments: "المصاريف",
        sidebar_education_assistant: "المساعد التعليمي",
        // Student Dashboard
        student_dashboard_title: "لوحة الطالب",
        btn_log_activity: "تسجيل النشاط",
        student_live_class: "🔴 فصل مباشر قيد التنفيذ!",
        btn_join_class: "الانضمام للفصل",
        btn_join_whiteboard: "الانضمام للسبورة",
        student_key_metrics: "المقاييس الرئيسية للطالب",
        student_upcoming_live: "الفصول المباشرة القادمة",
        msg_no_live_classes: "لا توجد فصول مباشرة مجدولة.",
        live_class_session: "فصل مباشر الآن",
        btn_join_now: "انضم الآن",
        student_level: "المستوى",
        student_my_courses: "دوراتي",
        msg_no_courses: "أنت غير مسجل في أي دورات بعد.",
        student_upcoming_assignments: "الواجبات والمشاريع القادمة",
        msg_loading_assignments: "جاري تحميل الواجبات...",
        tab_progress_graph: "📈 رسم التقدم",
        tab_activity_history: "📜 سجل النشاط",
        // Parent Portal
        parent_portal_title: "بوابة أولياء الأمور",
        label_select_child: "اختر طفلك",
        ph_child_id: "أدخل معرف الطالب للطفل (مثل S001)",
        btn_view_progress: "عرض التقدم",
        msg_enter_child_id: "أدخل معرف الطالب المقدم من المدرسة.",
        parent_overview_for: "نظرة عامة لـ",
        parent_key_updates: "تحديثات رئيسية",
        update_school_close: "تغلق المدرسة مبكراً غداً الساعة 2 ظهراً.",
        update_report_cards: "تم نشر بطاقات التقرير.",
        parent_academic_progress: "التقدم الأكاديمي",
        parent_teacher_feedback: "ملاحظات المعلم",
        msg_loading_feedback: "جاري تحميل الملاحظات...",
        parent_recent_marks: "الدرجات الحديثة",
        th_subject: "المادة",
        th_exam: "الامتحان",
        th_score: "الدرجة",
        parent_performance_chart: "مخطط الأداء",
        parent_report_cards: "بطاقات التقرير",
        term_1_report: "تقرير الفصل الأول",
        badge_download: "تحميل",
        // Modals - Roles
        modal_select_role: "تحديد الدور",
        role_principal: "المدير",
        role_super_admin: "المشرف العام",
        // Modals - Upload Resource
        modal_upload_resource: "رفع الموارد",
        label_res_title: "العنوان",
        label_res_category: "الفئة",
        opt_school_policy: "سياسة المدرسة",
        opt_exam_schedule: "جدول الامتحانات",
        opt_form: "نموذج إجازة/إداري",
        opt_other: "أخرى",
        label_res_desc: "الوصف",
        label_res_file: "ملف (PDF, Doc)",
        text_max_size: "الحد الأقصى للحجم 5 ميجابايت",
        // Modals - Permission Edit
        modal_edit_permission: "تعديل الصلاحيات",
        label_perm_code: "رمز الصلاحية",
        label_perm_title: "عنوان الصلاحية",
        btn_cancel: "إلغاء",
        btn_update: "تحديث",
        // Modals - Take Quiz
        modal_take_quiz: "مسابقة",
        btn_submit_quiz: "إرسال المسابقة",
        // Modals - Add Student
        modal_add_student: "➕ إضافة طالب جديد",
        label_student_id: "معرف الطالب",
        label_full_name: "الاسم الكامل",
        label_default_password: "كلمة المرور الافتراضية",
        label_grade: "الصف",
        // Modals - Access Card
        modal_access_card: "بطاقة دخول الطالب",
        label_topic: "الموضوع",
        ph_topic: "مثل: التمثيل الضوئي",
        // label_grade: "الصف", // Duplicated
        label_subject: "المادة",
        label_duration: "المدة (دقائق)",
        label_instructions: "تعليمات إضافية / سياق",
        ph_instructions: "مثل: التركيز على المفردات...",
        label_upload_pdf: "رفع ملف PDF للسياق (اختياري)",
        btn_generate_plan: "إنشاء الخطة",
        // Modals - Quiz
        modal_ai_quiz: "مولد الاختبارات الذكي",
        label_questions_count: "الأسئلة",
        btn_generate_quiz: "إنشاء الاختبار",
        // Modals - Schedule Class
        modal_schedule_class: "📅 جدولة فصل مباشر",
        label_date_time: "التاريخ والوقت",
        label_target_students: "الطلاب المستهدفون",
        label_filter_group: "تصفية حسب المجموعة",
        opt_all_students: "-- كل الطلاب --",
        label_select_all: "تحديد الكل",
        label_meet_link: "رابط Google Meet",
        ph_meet_link_long: "https://meet.google.com/...",
        help_meet_link: "انسخ والصق رابطًا من Google Meet أو Zoom.",
        btn_schedule: "جدولة",
        // Dashboard Metrics & Content
        dashboard_students: "الطلاب",
        dashboard_teachers: "المعلمين",
        dashboard_staff: "الموظفين",
        dashboard_awards: "الجوائز",
        metric_change_teachers: "! 3٪ من الشهر الماضي",
        metric_change_staff: "→ لا تغيير",
        metric_change_awards: "↑ 15٪ من الشهر الماضي",
        btn_schedule_class: "جدول الحصص",
        btn_ai_quiz: "مسابقة الذكاء الاصطناعي",
        btn_plan_lesson: "تخطيط الدرس",
        btn_whiteboard: "السبورة البيضاء",
        btn_export: "تصدير",
        btn_engagement_helper: "مساعد التفاعل",
        // Assignments & Payslips
        asg_active_title: "الواجبات النشطة",
        asg_active_subtitle: "أنشئ الواجبات وراجع التسليمات وتابع التقدم حسب الصف.",
        btn_create_assignment: "إنشاء واجب",
        asg_review_title: "قائمة المراجعة",
        btn_refresh: "تحديث",
        msg_loading_submissions: "جارٍ تحميل التسليمات...",
        msg_failed_load_submissions: "فشل تحميل التسليمات.",
        asg_review_empty: "لا توجد تسليمات للمراجعة.",
        marks_entry_title: "إدخال الدرجات",
        marks_select_assignment: "اختر الواجب",
        marks_load_submissions: "تحميل التسليمات",
        marks_select_prompt: "اختر واجبًا لعرض التسليمات.",
        msg_no_assignments: "لا توجد واجبات بعد.",
        msg_failed_load_assignments: "فشل تحميل الواجبات.",
        msg_assignment_requires_backend: "الواجبات تتطلب الخادم. افتح http://127.0.0.1:8000.",
        msg_fill_assignment_fields: "يرجى إدخال العنوان وتاريخ الاستحقاق والصف.",
        msg_create_assignment_failed: "فشل إنشاء الواجب.",
        msg_create_assignment_network_error: "خطأ في الشبكة أثناء إنشاء الواجب.",
        msg_assignment_submit_required: "يرجى كتابة شيء أو إضافة رابط.",
        msg_assignment_submit_success: "تم الإرسال بنجاح!",
        msg_assignment_submit_failed: "فشل الإرسال.",
        msg_assignment_submit_network_error: "خطأ في الشبكة.",
        btn_view_submissions: "عرض التسليمات",
        label_status: "الحالة",
        status_submitted: "تم التسليم",
        label_feedback: "ملاحظات",
        btn_save: "حفظ",
        btn_reassign: "إعادة تعيين",
        asg_modal_title: "📝 واجب جديد",
        label_title: "العنوان",
        label_description: "الوصف",
        label_class_grade: "الصف (الدرجة)",
        label_select_grade: "اختر الدرجة",
        label_points: "النقاط",
        label_section: "الشعبة",
        label_select_section_optional: "اختر الشعبة (اختياري)",
        label_due_date: "تاريخ الاستحقاق",
        btn_create: "إنشاء",
        payslip_title: "قسائم الرواتب",
        payslip_ytd: "منذ بداية السنة",
        payslip_net_pay_label: "صافي الراتب",
        payslip_latest: "آخر فترة دفع",
        payslip_latest_sub: "صافي الراتب • Sep 2024",
        payslip_payment_method: "طريقة الدفع",
        payslip_account_masked: "الحساب •••• 2391",
        payslip_recent: "القسائم الأخيرة",
        payslip_download_all: "تنزيل الكل",
        payslip_processed_paid: "تمت المعالجة: Oct 01, 2024 • الحالة: مدفوع",
        payslip_view_details: "عرض التفاصيل",
        payslip_gross: "الإجمالي: $5,000",
        payslip_deductions: "الخصومات: $880",
        payslip_taxes: "الضرائب: $620",
        payslip_print_title: "طباعة القسائم",
        payslip_generate_pdf: "إنشاء PDF للقسيمة",
        payslip_pay_period: "فترة الدفع",
        payslip_delivery: "التسليم",
        payslip_download_pdf: "تنزيل PDF",
        payslip_email_me: "أرسلها إلى بريدي",
        payslip_generate_btn: "إنشاء PDF",
        payslip_preview: "معاينة القسيمة",
        payslip_employee_id: "معرّف الموظف: T-1024",
        payslip_processed_date: "تمت المعالجة: Oct 01, 2024",
        payslip_earnings: "المستحقات",
        payslip_base_salary: "الراتب الأساسي",
        payslip_allowance: "البدلات",
        payslip_deduction_label: "الخصومات",
        payslip_tax: "الضريبة",
        payslip_insurance: "التأمين",
        pay_advance_title: "طلب سلفة راتب",
        pay_advance_amount: "المبلغ المطلوب",
        pay_advance_reason: "السبب",
        pay_advance_repayment: "طريقة السداد",
        pay_advance_next_period: "الفترة القادمة",
        pay_advance_two_periods: "فترتان",
        pay_advance_submit: "إرسال الطلب",
        pay_advance_recent: "الطلبات الأخيرة",
        pay_advance_label: "سلفة",
        pay_advance_submitted: "تم الإرسال: Aug 12, 2024",
        pay_advance_pending: "قيد الانتظار",
        pay_advance_approved: "موافق عليه",
        dashboard_live_controls: "ضوابط الفصل المباشر",
        dashboard_now: "الآن",
        ph_meet_link: "رابط Google Meet",
        btn_start: "يبدأ",
        btn_end: "إنهاء",
        dashboard_calendar: "التقويم",
        dashboard_upcoming_events: "الأحداث القادمة",
        dashboard_performance_dist: "توزيع الأداء",
        dashboard_class_avg_score: "متوسط ​​درجة النشاط",
        // Headers
        header_messages: "الرسائل",
        header_notifications: "إشعارات",
        header_my_profile: "ملفي الشخصي",
        header_logout: "تسجيل الخروج",
        ph_search: "بحث...",
        stat_active_students: "الطلاب النشطون",
        nav_teachers: "المعلمون",
        nav_students: "الطلاب",
        nav_schools: "المدارس",
        nav_resources: "الموارد",
        btn_log_in: "تسجيل الدخول",
        text_back: "رجوع",
        login_not_a: "لست",
        login_switch_role: "تبديل الدور",
        login_student_login: "دخول الطالب",
        login_teacher_portal: "بوابة المعلم",
        login_parent_access: "بوابة ولي الأمر",
        login_principal_login: "دخول المدير",
        login_super_admin: "مشرف عام",
        login_root_admin_portal: "بوابة المشرف الجذر",
        login_generic: "دخول",
        role_student: "طالب",
        role_teacher: "معلم",
        role_parent: "ولي أمر",
        role_others: "أخرى",
        role_admin: "مسؤول",
        role_root_admin: "مسؤول جذر",
        hero_heading: "حيث تتحول الفصول\nإلى مجتمعات",
        hero_subtitle: "تمكين المؤسسات التعليمية من خلال حلول مبتكرة",
        hero_get_started_as: "ابدأ كـ...",
        feat_why_title: "لماذا Noble Nexus؟",
        feat_main_title: "كل ما تحتاجه للتميّز",
        feat_analytics_title: "تحليلات ذكية",
        feat_analytics_desc: "تتبّع الأداء الأكاديمي عبر لوحات واضحة مدعومة بالذكاء الاصطناعي.",
        feat_live_title: "فصول مباشرة",
        feat_live_desc: "مؤتمرات فيديو مدمجة للتعلّم عن بعد بسلاسة من لوحة التحكم.",
        feat_ai_title: "إرشاد بالذكاء الاصطناعي",
        feat_ai_desc: "مسارات تعلّم مخصصة وتغذية راجعة تلقائية لكل طالب.",
        about_title: "حول ClassBridge",
        about_main_title: "تمكين مستقبل التعليم",
        about_desc: "صُمم ClassBridge لردم الفجوة بين التعليم التقليدي والتقنية الحديثة.",
        about_teachers: "للمعلمين",
        about_teachers_desc: "إدارة الصفوف بسهولة مع حضور ذكي وتصحيح تلقائي وتخطيط دروس ذكي.",
        about_students: "للطلاب",
        about_students_desc: "وصول إلى مسارات تعلم مخصصة وتتبع التقدم بشكل لحظي.",
        about_parents: "لأولياء الأمور",
        about_parents_desc: "ابقَ على اطلاع بالحضور والأداء الأكاديمي وفعاليات المدرسة.",
        btn_discover_more: "اكتشف المزيد",
        stat_engagement: "معدل التفاعل",
        stat_ai_support: "دعم الذكاء الاصطناعي",
        footer_company: "الشركة",
        footer_about: "من نحن",
        footer_press: "الصحافة",
        footer_careers: "الوظائف",
        footer_engineering: "الهندسة",
        footer_accessibility: "إمكانية الوصول",
        footer_resources: "الموارد",
        footer_big_ideas: "أفكار كبيرة",
        footer_training: "التدريب",
        footer_remote_learning: "التعلم عن بُعد",
        footer_support: "الدعم",
        footer_help_center: "مركز المساعدة",
        footer_contact: "اتصل بنا",
        footer_privacy: "مركز الخصوصية",
        footer_cookies: "إعدادات ملفات تعريف الارتباط",
        footer_get_app: "احصل على التطبيق",
        footer_terms: "الشروط",
        text_scan_visit: "امسح للزيارة",
        text_product_by: "منتج من Noble Nexus",
        text_a_product_by: "منتج من",
        footer_noble_nexus_plus: "نوبل نيكسس بلس",
        feat_modern_title: "مصمم للفصل الحديث",
        feat_quiz_gen: "مولد الاختبارات",
        feat_quiz_desc: "ارفع PDF وسيقوم الذكاء الاصطناعي بإنشاء أسئلة وإجابات خلال ثوانٍ.",
        link_try_generator: "جرّب المولد ←",
        feat_student_insights: "رؤى الطالب",
        feat_student_insights_desc: "تجاوز الدرجات لفهم من يحتاج دعمًا أو تحديًا أكبر.",
        link_view_report: "عرض تقرير نموذجي ←",
        feat_hybrid: "فصل هجين",
        feat_hybrid_desc: "انتقال سلس بين التعليم الحضوري والتعليم عن بعد.",
        link_see_how: "شاهد كيف ←",
        cta_ready_transform: "هل أنت جاهز لتحويل أسلوب التدريس؟",
        btn_join_free: "انضم إلى Noble Nexus مجانًا"
    },
    hi: {
        login_welcome: "Noble Nexus में आपका स्वागत है",
        login_subtitle: "Noble Nexus में साइन इन करें",
        label_username: "उपयोगकर्ता नाम / छात्र आईडी",
        label_password: "पासवर्ड",
        link_forgot_password: "पासवर्ड भूल गए?",
        btn_signin: "साइन इन करें",
        btn_signin_microsoft: "Microsoft के साथ साइन इन करें",
        text_or: "या",
        text_new_user: "नया उपयोगकर्ता?",
        link_signup: "साइन अप करें",
        link_help: "मदद चाहिए? संपर्क करें",
        msg_enter_credentials: "कृपया उपयोगकर्ता नाम और पासवर्ड दर्ज करें।",
        msg_checking: "क्रेडेंशियल्स की जाँच की जा रही है...",
        msg_welcome: "स्वागत है, {user_id}",
        msg_login_failed: "लॉगिन विफल",
        msg_network_error: "नेटवर्क त्रुटि: {error}",
        msg_google_verify: "Google टोकन सत्यापित किया जा रहा है...",
        msg_microsoft_conn: "Microsoft से कनेक्ट हो रहा है...",
        msg_microsoft_verify: "Microsoft टोकन सत्यापित किया जा रहा है...",
        // Sidebar & Dashboard
        sidebar_dashboard: "डैशबोर्ड",
        sidebar_my_courses: "मेरे पाठ्यक्रम",
        sidebar_course_list: "पाठ्यक्रम सूची",
        sidebar_assignments: "असाइनमेंट",
        sidebar_exams: "परीक्षाएँ",
        sidebar_upcoming_exams: "आगामी परीक्षाएँ",
        sidebar_results: "परिणाम",
        sidebar_profile: "प्रोफ़ाइल",
        sidebar_view_profile: "प्रोफ़ाइल देखें",
        sidebar_settings: "सेटिंग्स",
        sidebar_communication: "संचार",
        sidebar_lms: "पाठ्यक्रम (LMS)",
        sidebar_ai_assistant: "AI सहायक",
        sidebar_timetable: "समय सारिणी",
        sidebar_view_timetable: "समय सारिणी देखें",
        sidebar_attendance: "उपस्थिति",
        sidebar_take_attendance: "उपस्थिति लें",
        sidebar_attendance_sheet: "उपस्थिति पत्रक",
        sidebar_monthly_report: "माहवार रिपोर्ट",
        sidebar_approve_leave: "छुट्टी मंजूर/अस्वीकार",
        sidebar_apply_leave: "छुट्टी आवेदन",
        sidebar_assignment_group: "असाइनमेंट",
        sidebar_create_assignment: "नया असाइनमेंट",
        sidebar_view_submitted: "प्रस्तुत देखें",
        sidebar_approve_reassign: "मंजूर / पुनः सौंपें",
        sidebar_enter_marks: "अंक दर्ज करें",
        sidebar_online_test: "ऑनलाइन टेस्ट",
        sidebar_question_bank: "प्रश्न बैंक",
        sidebar_create_test: "टेस्ट बनाएं",
        sidebar_assign_max_marks: "अंक सौंपें",
        sidebar_view_test_results: "परिणाम देखें",
        sidebar_progress_card: "प्रगति कार्ड",
        sidebar_enter_progress: "प्रगति अंक दर्ज",
        sidebar_save_publish: "सहेजें और प्रकाशित",
        sidebar_view_progress: "प्रगति कार्ड देखें",
        sidebar_pay_slips: "वेतन पर्ची",
        sidebar_view_payslips: "वेतन पर्ची देखें",
        sidebar_students: "छात्र",
        sidebar_add_student: "छात्र जोड़ें",
        sidebar_student_list: "छात्र सूची",
        sidebar_reports: "रिपोर्ट",
        sidebar_attendance_report: "उपस्थिति रिपोर्ट",
        sidebar_performance_report: "प्रदर्शन रिपोर्ट",
        sidebar_resource_library: "संसाधन पुस्तकालय",
        sidebar_ai_copilot: "AI सह-पायलट",
        sidebar_roles_perms: "भूमिकाएँ",
        sidebar_staff_faculty: "कर्मचारी",
        sidebar_system_settings: "सिस्टम सेटिंग्स",
        sidebar_academic_progress: "शैक्षणिक प्रगति",
        sidebar_fees_payments: "शुल्क और भुगतान",
        sidebar_education_assistant: "शिक्षा सहायक",
        // Student Dashboard
        student_dashboard_title: "छात्र डैशबोर्ड",
        btn_log_activity: "गतिविधि दर्ज करें",
        student_live_class: "🔴 लाइव क्लास चल रही है!",
        btn_join_class: "क्लास में शामिल हों",
        btn_join_whiteboard: "व्हाइटबोर्ड में शामिल हों",
        student_key_metrics: "छात्र प्रमुख मेट्रिक्स",
        student_upcoming_live: "आगामी लाइव क्लासेज",
        msg_no_live_classes: "कोई लाइव क्लास निर्धारित नहीं है।",
        live_class_session: "लाइव क्लास सत्र में",
        btn_join_now: "अभी शामिल हों",
        student_level: "स्तर",
        student_my_courses: "मेरे पाठ्यक्रम",
        msg_no_courses: "आप अभी किसी पाठ्यक्रम में नामांकित नहीं हैं।",
        student_upcoming_assignments: "आगामी असाइनमेंट और परियोजनाएं",
        msg_loading_assignments: "असाइनमेंट लोड हो रहे हैं...",
        tab_progress_graph: "📈 प्रगति ग्राफ",
        tab_activity_history: "📜 गतिविधि इतिहास",
        // Parent Portal
        parent_portal_title: "अभिभावक पोर्टल",
        label_select_child: "अपने बच्चे का चयन करें",
        ph_child_id: "बच्चे का छात्र आईडी दर्ज करें (उदा. S001)",
        btn_view_progress: "प्रगति देखें",
        msg_enter_child_id: "स्कूल द्वारा प्रदान किया गया छात्र आईडी दर्ज करें।",
        parent_overview_for: "के लिए अवलोकन",
        parent_key_updates: "महत्वपूर्ण अपडेट",
        update_school_close: "स्कूल कल दोपहर 2 बजे जल्दी बंद हो जाएगा।",
        update_report_cards: "रिपोर्ट कार्ड प्रकाशित किए गए हैं।",
        parent_academic_progress: "शैक्षणिक प्रगति",
        parent_teacher_feedback: "शिक्षक की प्रतिक्रिया",
        msg_loading_feedback: "प्रतिक्रिया लोड हो रही है...",
        parent_recent_marks: "हालिया अंक",
        th_subject: "विषय",
        th_exam: "परीक्षा",
        th_score: "अंक",
        parent_performance_chart: "प्रदर्शन चार्ट",
        parent_report_cards: "रिपोर्ट कार्ड",
        term_1_report: "टर्म 1 रिपोर्ट",
        badge_download: "डाउनलोड",
        // Modals - Roles
        modal_select_role: "भूमिका चुनें",
        role_principal: "प्रधानाचार्य",
        role_super_admin: "सुपर एडमिन",
        // Modals - Upload Resource
        modal_upload_resource: "संसाधन अपलोड करें",
        label_res_title: "शीर्षक",
        label_res_category: "श्रेणी",
        opt_school_policy: "स्कूल नीति",
        opt_exam_schedule: "परीक्षा अनुसूची",
        opt_form: "छुट्टी/एडमिन फॉर्म",
        opt_other: "अन्य",
        label_res_desc: "विवरण",
        label_res_file: "फ़ाइल (PDF, Doc)",
        text_max_size: "अधिकतम आकार 5MB",
        // Modals - Permission Edit
        modal_edit_permission: "अनुमति संपादित करें",
        label_perm_code: "अनुमति कोड",
        label_perm_title: "अनुमति शीर्षक",
        btn_cancel: "रद्द करें",
        btn_update: "अपडेट करें",
        // Modals - Take Quiz
        modal_take_quiz: "प्रश्नोत्तरी",
        btn_submit_quiz: "प्रश्नोत्तरी जमा करें",
        // Modals - Add Student
        modal_add_student: "➕ नया छात्र जोड़ें",
        label_student_id: "छात्र आईडी",
        label_full_name: "पूरा नाम",
        label_default_password: "डिफ़ॉल्ट पासवर्ड",
        label_grade: "कक्षा",
        // Modals - Access Card
        modal_access_card: "छात्र एक्सेस कार्ड",
        label_topic: "विषय",
        ph_topic: "उदाहरण: प्रकाश संश्लेषण",
        // label_grade: "कक्षा", // Duplicated
        label_subject: "विषय",
        label_duration: "अवधि (मिनट)",
        label_instructions: "अतिरिक्त निर्देश / संदर्भ",
        ph_instructions: "उदा. शब्दावली पर ध्यान दें...",
        label_upload_pdf: "पीडीएफ संदर्भ अपलोड करें (वैकल्पिक)",
        btn_generate_plan: "पाठ योजना बनाएं",
        // Modals - Quiz
        modal_ai_quiz: "AI क्विज़ जेनरेटर",
        label_questions_count: "प्रश्न",
        btn_generate_quiz: "क्विज़ बनाएं",
        // Modals - Schedule Class
        modal_schedule_class: "📅 लाइव क्लास शेड्यूल करें",
        label_date_time: "दिनांक और समय",
        label_target_students: "लक्षित छात्र",
        label_filter_group: "समूह द्वारा फ़िल्टर करें",
        opt_all_students: "-- सभी छात्र --",
        label_select_all: "सभी चुनें",
        label_meet_link: "गूगल मीट लिंक",
        ph_meet_link_long: "https://meet.google.com/...",
        help_meet_link: "गूगल मीट या ज़ूम से लिंक कॉपी करके पेस्ट करें।",
        btn_schedule: "शेड्यूल करें",
        // Dashboard Metrics & Content
        dashboard_students: "छात्र",
        dashboard_teachers: "शिक्षक",
        dashboard_staff: "कर्मचारी",
        dashboard_awards: "पुरस्कार",
        metric_change_teachers: "! पिछले महीने से 3%",
        metric_change_staff: "→ कोई बदलाव नहीं",
        metric_change_awards: "↑ पिछले महीने से 15%",
        btn_schedule_class: "कक्षा शेड्यूल करें",
        btn_ai_quiz: "AI क्विज़",
        btn_plan_lesson: "पाठ योजना",
        btn_whiteboard: "व्हाइटबोर्ड",
        btn_export: "निर्यात",
        btn_engagement_helper: "एंगेजमेंट हेल्पर",
        // Assignments & Payslips
        asg_active_title: "सक्रिय असाइनमेंट",
        asg_active_subtitle: "असाइनमेंट बनाएँ, सबमिशन देखें और कक्षा अनुसार प्रगति ट्रैक करें।",
        btn_create_assignment: "असाइनमेंट बनाएँ",
        asg_review_title: "समीक्षा कतार",
        btn_refresh: "रिफ्रेश",
        msg_loading_submissions: "सबमिशन लोड हो रहे हैं...",
        msg_failed_load_submissions: "सबमिशन लोड नहीं हो सके।",
        asg_review_empty: "कोई सबमिशन लंबित नहीं है।",
        marks_entry_title: "अंक प्रविष्टि",
        marks_select_assignment: "असाइनमेंट चुनें",
        marks_load_submissions: "सबमिशन लोड करें",
        marks_select_prompt: "सबमिशन देखने के लिए असाइनमेंट चुनें।",
        msg_no_assignments: "अभी कोई असाइनमेंट नहीं है।",
        msg_failed_load_assignments: "असाइनमेंट लोड नहीं हो सके।",
        msg_assignment_requires_backend: "असाइनमेंट के लिए बैकएंड आवश्यक है। http://127.0.0.1:8000 पर खोलें।",
        msg_fill_assignment_fields: "कृपया शीर्षक, अंतिम तिथि और कक्षा (ग्रेड) भरें।",
        msg_create_assignment_failed: "असाइनमेंट नहीं बन सका।",
        msg_create_assignment_network_error: "असाइनमेंट बनाते समय नेटवर्क त्रुटि।",
        msg_assignment_submit_required: "कृपया कुछ लिखें या लिंक दें।",
        msg_assignment_submit_success: "सफलतापूर्वक सबमिट हुआ!",
        msg_assignment_submit_failed: "सबमिशन असफल।",
        msg_assignment_submit_network_error: "नेटवर्क त्रुटि।",
        btn_view_submissions: "सबमिशन देखें",
        label_status: "स्थिति",
        status_submitted: "सबमिट",
        label_feedback: "फ़ीडबैक",
        btn_save: "सहेजें",
        btn_reassign: "पुनः असाइन",
        asg_modal_title: "📝 नया असाइनमेंट",
        label_title: "शीर्षक",
        label_description: "विवरण",
        label_class_grade: "कक्षा (ग्रेड)",
        label_select_grade: "ग्रेड चुनें",
        label_points: "अंक",
        label_section: "सेक्शन",
        label_select_section_optional: "सेक्शन चुनें (वैकल्पिक)",
        label_due_date: "अंतिम तिथि",
        btn_create: "बनाएँ",
        payslip_title: "मेरे वेतन पर्चे",
        payslip_ytd: "वर्ष-से-तारीख",
        payslip_net_pay_label: "नेट पे",
        payslip_latest: "हाल की भुगतान अवधि",
        payslip_latest_sub: "नेट पे • Sep 2024",
        payslip_payment_method: "भुगतान का तरीका",
        payslip_account_masked: "खाता •••• 2391",
        payslip_recent: "हाल के वेतन पर्चे",
        payslip_download_all: "सभी डाउनलोड करें",
        payslip_processed_paid: "प्रोसेस्ड: Oct 01, 2024 • स्थिति: भुगतान",
        payslip_view_details: "विवरण देखें",
        payslip_gross: "ग्रॉस: $5,000",
        payslip_deductions: "कटौती: $880",
        payslip_taxes: "कर: $620",
        payslip_print_title: "वेतन पर्चे प्रिंट करें",
        payslip_generate_pdf: "वेतन पर्चा PDF बनाएं",
        payslip_pay_period: "भुगतान अवधि",
        payslip_delivery: "डिलीवरी",
        payslip_download_pdf: "PDF डाउनलोड करें",
        payslip_email_me: "मुझे ईमेल करें",
        payslip_generate_btn: "PDF बनाएं",
        payslip_preview: "वेतन पर्चा पूर्वावलोकन",
        payslip_employee_id: "कर्मचारी आईडी: T-1024",
        payslip_processed_date: "प्रोसेस्ड: Oct 01, 2024",
        payslip_earnings: "कमाई",
        payslip_base_salary: "मूल वेतन",
        payslip_allowance: "भत्ता",
        payslip_deduction_label: "कटौतियाँ",
        payslip_tax: "कर",
        payslip_insurance: "बीमा",
        pay_advance_title: "वेतन अग्रिम के लिए आवेदन करें",
        pay_advance_amount: "आवश्यक राशि",
        pay_advance_reason: "कारण",
        pay_advance_repayment: "पसंदीदा वापसी",
        pay_advance_next_period: "अगली भुगतान अवधि",
        pay_advance_two_periods: "दो भुगतान अवधि",
        pay_advance_submit: "अनुरोध भेजें",
        pay_advance_recent: "हाल के अनुरोध",
        pay_advance_label: "अग्रिम",
        pay_advance_submitted: "जमा: Aug 12, 2024",
        pay_advance_pending: "लंबित",
        pay_advance_approved: "स्वीकृत",
        dashboard_live_controls: "लाइव क्लास नियंत्रण",
        dashboard_now: "अभी",
        ph_meet_link: "Google मीट लिंक",
        btn_start: "शुरू",
        btn_end: "समाप्त",
        dashboard_calendar: "कैलेंडर",
        dashboard_upcoming_events: "आगामी कार्यक्रम",
        dashboard_performance_dist: "प्रदर्शन वितरण",
        dashboard_class_avg_score: "कक्षा औसत गतिविधि स्कोर",
        // Headers
        header_messages: "संदेश",
        header_notifications: "सूचनाएं",
        header_my_profile: "मेरी प्रोफ़ाइल",
        header_logout: "लॉग आउट",
        ph_search: "यहाँ खोजें...",
        // New Added Keys
        header_view_all_messages: "सभी संदेश देखें",
        header_mark_read: "सभी को पढ़ा हुआ चिह्नित करें",
        notif_sys_maint: "सिस्टम रखरखाव",
        notif_sys_maint_desc: "आज रात 12 बजे के लिए अनुसूचित।",
        notif_assign_sub: "असाइनमेंट सबमिट किया गया",
        notif_assign_sub_desc: "एलिस स्मिथ ने \"मैथ एचडब्ल्यू\" सबमिट किया।",
        login_journey_title: "आपकी सीखने की यात्रा जारी है",
        login_journey_desc: "अपने पाठ्यक्रमों, लाइव कक्षाओं और व्यक्तिगत एआई अंतर्दृष्टि तक पहुंचने के लिए लॉग इन करें।",
        stat_pass_rate: "उत्तीर्ण दर",
        stat_access: "पहुँच",
        stat_students: "छात्र",
        footer_company: "कंपनी",
        footer_about: "हमारे बारे में",
        footer_press: "प्रेस",
        footer_careers: "करियर",
        footer_engineering: "इंजीनियरिंग",
        footer_accessibility: "पहुँच-योग्यता",
        footer_resources: "संसाधन",
        footer_big_ideas: "बड़े विचार",
        footer_training: "प्रशिक्षण",
        footer_remote_learning: "दूरस्थ शिक्षा",
        footer_support: "सहायता",
        footer_help_center: "सहायता केंद्र",
        footer_contact: "संपर्क करें",
        footer_privacy: "गोपनीयता केंद्र",
        footer_cookies: "कुकी सेटिंग्स",
        footer_get_app: "ऐप प्राप्त करें",
        footer_terms: "शर्तें",
        text_scan_visit: "विजिट करने के लिए स्कैन करें",
        text_product_by: "Noble Nexus का एक उत्पाद",
        text_a_product_by: "एक उत्पाद",
        footer_noble_nexus_plus: "नोबल नेक्सस प्लस",
        // Landing Page Mock Data (Hindi)
        feat_why_title: "नोबल नेक्सस क्यों?",
        feat_main_title: "उत्कृष्टता के लिए आपको जो कुछ भी चाहिए",
        feat_analytics_title: "स्मार्ट एनालिटिक्स",
        feat_analytics_desc: "स्पष्ट, एआई-संचालित विज़ुअलाइज़ेशन के साथ शैक्षणिक प्रदर्शन के रुझानों को ट्रैक करें जो छात्रों को तेजी से सुधारने में मदद करते हैं।",
        feat_live_title: "लाइव क्लासरूम",
        feat_live_desc: "एकीकृत वीडियो कॉन्फ्रेंसिंग आपके डैशबोर्ड से सीधे निर्बाध दूरस्थ शिक्षण सत्रों की अनुमति देती है।",
        feat_ai_title: "एआई मार्गदर्शन",
        feat_ai_desc: "प्रत्येक छात्र की अनूठी यात्रा के लिए डिज़ाइन किए गए व्यक्तिगत शिक्षण पथ और स्वचालित प्रतिक्रिया का अनुभव करें।",
        about_title: "क्लासब्रिज के बारे में",
        about_main_title: "शिक्षा के भविष्य को सशक्त बनाना",
        about_desc: "क्लासब्रिज को पारंपरिक स्कूली शिक्षा और आधुनिक तकनीक के बीच की खाई को पाटने के लिए डिज़ाइन किया गया है। हम एक एकीकृत पारिस्थितिकी तंत्र प्रदान करते हैं जहां सीखना नवाचार से मिलता है:",
        about_teachers: "शिक्षकों के लिए",
        about_teachers_desc: "एआई-संचालित उपस्थिति, स्वचालित ग्रेडिंग और स्मार्ट पाठ योजना उपकरणों के साथ कक्षाओं का प्रबंधन आसानी से करें।",
        about_students: "छात्रों के लिए",
        about_students_desc: "व्यक्तिगत शिक्षण पथों तक पहुंचें, वास्तविक समय की प्रगति को ट्रैक करें, और गेमिफाइड शिक्षा लक्ष्यों के साथ जुड़े रहें।",
        about_parents: "माता-पिता के लिए",
        about_parents_desc: "उपस्थिति, शैक्षणिक प्रदर्शन और स्कूल कार्यक्रमों पर त्वरित अपडेट के साथ सूचित रहें।",
        btn_discover_more: "और अधिक खोजें",
        stat_engagement: "जुड़ाव दर",
        stat_ai_support: "एआई सहायता",
        stat_active_students: "सक्रिय छात्र",
        nav_teachers: "शिक्षक",
        nav_students: "छात्र",
        nav_schools: "स्कूल",
        nav_resources: "संसाधन",
        btn_log_in: "लॉग इन",
        text_back: "वापस",
        login_not_a: "क्या आप",
        login_switch_role: "भूमिका बदलें",
        login_student_login: "छात्र लॉगिन",
        login_teacher_portal: "शिक्षक पोर्टल",
        login_parent_access: "अभिभावक प्रवेश",
        login_principal_login: "प्रधानाचार्य लॉगिन",
        login_super_admin: "सुपर एडमिन",
        login_root_admin_portal: "रूट एडमिन पोर्टल",
        login_generic: "लॉगिन",
        role_student: "छात्र",
        role_teacher: "शिक्षक",
        role_parent: "अभिभावक",
        role_others: "अन्य",
        role_admin: "एडमिन",
        role_root_admin: "रूट एडमिन",
        hero_heading: "जहां कक्षाएं\nसमुदाय बनती हैं",
        hero_subtitle: "नवाचारी समाधानों के माध्यम से शैक्षणिक संस्थानों को सशक्त बनाना",
        hero_get_started_as: "इस रूप में शुरू करें...",
        feat_modern_title: "आधुनिक कक्षा के लिए निर्मित",
        feat_quiz_gen: "क्विज़ जेनरेटर",
        feat_quiz_desc: "एक पीडीएफ अध्याय अपलोड करें, और हमारा एआई सेकंड में उत्तर कुंजी के साथ 20 अलग-अलग प्रश्न तैयार करता है।",
        link_try_generator: "जेनरेटर आज़माएं →",
        feat_student_insights: "छात्र अंतर्दृष्टि",
        feat_student_insights_desc: "ग्रेड से परे। देखें कि कौन कड़ी मेहनत कर रहा है लेकिन संघर्ष कर रहा है, और किसे अधिक चुनौतीपूर्ण सामग्री की आवश्यकता है।",
        link_view_report: "नमूना रिपोर्ट देखें →",
        feat_hybrid: "हाइब्रिड क्लासरूम",
        feat_hybrid_desc: "वीडियो लॉजिक के साथ इन-पर्सन और रिमोट शिक्षण के बीच निर्बाध रूप से स्विच करें।",
        link_see_how: "देखें कैसे →",
        cta_ready_transform: "क्या आप अपने शिक्षण को बदलने के लिए तैयार हैं?",
        btn_join_free: "मुफ्त में नोबल नेक्सस से जुड़ें"
    },
    ja: {
        login_welcome: "Noble Nexusへようこそ",
        login_subtitle: "Noble Nexusポータルにサインイン",
        label_username: "ユーザー名 / 学生ID",
        label_password: "パスワード",
        link_forgot_password: "パスワードをお忘れですか？",
        btn_signin: "サインイン",
        btn_signin_microsoft: "Microsoftでサインイン",
        text_or: "または",
        text_new_user: "新規ユーザーですか？",
        link_signup: "サインアップ",
        link_help: "助けが必要ですか？",
        msg_enter_credentials: "ユーザー名とパスワードを入力してください。",
        msg_checking: "認証情報を確認中...",
        msg_welcome: "ようこそ、{user_id}",
        msg_login_failed: "ログインに失敗しました",
        msg_network_error: "ネットワークエラー: {error}",
        msg_google_verify: "Googleトークンを確認中...",
        msg_microsoft_conn: "Microsoftに接続中...",
        msg_microsoft_verify: "Microsoftトークンを確認中...",
        // Sidebar & Dashboard
        sidebar_dashboard: "ダッシュボード",
        sidebar_my_courses: "マイコース",
        sidebar_course_list: "コース一覧",
        sidebar_assignments: "課題",
        sidebar_exams: "試験",
        sidebar_upcoming_exams: "今後の試験",
        sidebar_results: "成績",
        sidebar_profile: "プロフィール",
        sidebar_view_profile: "プロフィールを見る",
        sidebar_settings: "設定",
        sidebar_communication: "連絡",
        sidebar_lms: "コース (LMS)",
        sidebar_ai_assistant: "AIアシスタント",
        sidebar_timetable: "時間割",
        sidebar_view_timetable: "時間割を見る",
        sidebar_attendance: "出席",
        sidebar_take_attendance: "出席を取る",
        sidebar_attendance_sheet: "クラス出席表",
        sidebar_monthly_report: "月次レポート",
        sidebar_approve_leave: "休暇承認",
        sidebar_apply_leave: "休暇申請",
        sidebar_assignment_group: "課題",
        sidebar_create_assignment: "課題作成",
        sidebar_view_submitted: "提出物",
        sidebar_approve_reassign: "承認/再割当",
        sidebar_enter_marks: "成績入力",
        sidebar_online_test: "オンラインテスト",
        sidebar_question_bank: "問題バンク",
        sidebar_create_test: "テスト作成",
        sidebar_assign_max_marks: "配点設定",
        sidebar_view_test_results: "結果を見る",
        sidebar_progress_card: "成績表",
        sidebar_enter_progress: "成績入力",
        sidebar_save_publish: "保存して公開",
        sidebar_view_progress: "成績表を見る",
        sidebar_pay_slips: "給与明細",
        sidebar_view_payslips: "明細を見る",
        sidebar_students: "生徒",
        sidebar_add_student: "生徒を追加",
        sidebar_student_list: "生徒一覧",
        sidebar_reports: "レポート",
        sidebar_attendance_report: "出席レポート",
        sidebar_performance_report: "成績レポート",
        sidebar_resource_library: "ライブラリ",
        sidebar_ai_copilot: "AIコパイロット",
        sidebar_roles_perms: "ロールと権限",
        sidebar_staff_faculty: "教職員",
        sidebar_system_settings: "システム設定",
        sidebar_academic_progress: "学業成績",
        sidebar_fees_payments: "学費と支払い",
        sidebar_education_assistant: "教育アシスタント",
        // Student Dashboard
        student_dashboard_title: "学生ダッシュボード",
        btn_log_activity: "活動記録",
        student_live_class: "🔴 ライブ授業中！",
        btn_join_class: "授業に参加",
        btn_join_whiteboard: "ホワイトボードに参加",
        student_key_metrics: "学生の主要指標",
        student_upcoming_live: "今後のライブ授業",
        msg_no_live_classes: "予定されているライブ授業はありません。",
        live_class_session: "ライブ授業開催中",
        btn_join_now: "今すぐ参加",
        student_level: "レベル",
        student_my_courses: "マイコース",
        msg_no_courses: "まだどのコースにも登録されていません。",
        student_upcoming_assignments: "今後の課題とプロジェクト",
        msg_loading_assignments: "課題を読み込み中...",
        tab_progress_graph: "📈 進捗グラフ",
        tab_activity_history: "📜 活動履歴",
        // Parent Portal
        parent_portal_title: "保護者ポータル",
        label_select_child: "お子様を選択",
        ph_child_id: "学生IDを入力 (例: S001)",
        btn_view_progress: "進捗を見る",
        msg_enter_child_id: "学校から提供された学生IDを入力してください。",
        parent_overview_for: "の概要",
        parent_key_updates: "重要な更新",
        update_school_close: "明日は午後2時に早期下校となります。",
        update_report_cards: "成績表が公開されました。",
        parent_academic_progress: "学業成績",
        parent_teacher_feedback: "先生からのフィードバック",
        msg_loading_feedback: "フィードバックを読み込み中...",
        parent_recent_marks: "最近の成績",
        th_subject: "科目",
        th_exam: "試験",
        th_score: "スコア",
        parent_performance_chart: "成績チャート",
        parent_report_cards: "成績表",
        term_1_report: "1学期レポート",
        badge_download: "ダウンロード",
        // Modals - Roles
        modal_select_role: "役割を選択",
        role_principal: "校長",
        role_super_admin: "スーパー管理者",
        // Modals - Upload Resource
        modal_upload_resource: "リソースをアップロード",
        label_res_title: "タイトル",
        label_res_category: "カテゴリ",
        opt_school_policy: "学校の方針",
        opt_exam_schedule: "試験スケジュール",
        opt_form: "休暇/管理者フォーム",
        opt_other: "その他",
        label_res_desc: "説明",
        label_res_file: "ファイル (PDF, Doc)",
        text_max_size: "最大サイズ 5MB",
        // Modals - Permission Edit
        modal_edit_permission: "権限を編集",
        label_perm_code: "権限コード",
        label_perm_title: "権限タイトル",
        btn_cancel: "キャンセル",
        btn_update: "更新",
        // Modals - Take Quiz
        modal_take_quiz: "クイズ",
        btn_submit_quiz: "クイズを提出",
        // Modals - Add Student
        modal_add_student: "➕ 新しい生徒を追加",
        label_student_id: "生徒ID",
        label_full_name: "氏名",
        label_default_password: "デフォルトパスワード",
        label_grade: "学年",
        // Modals - Access Card
        modal_access_card: "生徒アクセスカード",
        label_topic: "トピック",
        ph_topic: "例：光合成",
        // label_grade: "学年", // Duplicated
        label_subject: "科目",
        label_duration: "時間 (分)",
        label_instructions: "追加の指示 / コンテキスト",
        ph_instructions: "例: 語彙に焦点を当てる...",
        label_upload_pdf: "PDFコンテキストをアップロード (任意)",
        btn_generate_plan: "授業プランを作成",
        // Modals - Quiz
        modal_ai_quiz: "AIクイズ生成",
        label_questions_count: "質問数",
        btn_generate_quiz: "クイズを作成",
        // Modals - Schedule Class
        modal_schedule_class: "📅 ライブ授業を予約",
        label_date_time: "日時",
        label_target_students: "対象の生徒",
        label_filter_group: "グループでフィルタ",
        opt_all_students: "-- 全生徒 --",
        label_select_all: "すべて選択",
        label_meet_link: "Google Meetリンク",
        ph_meet_link_long: "https://meet.google.com/...",
        help_meet_link: "Google MeetまたはZoomのリンクをコピーして貼り付けてください。",
        btn_schedule: "予約する",
        // Dashboard Metrics & Content
        dashboard_students: "生徒",
        dashboard_teachers: "先生",
        dashboard_staff: "職員",
        dashboard_awards: "受賞",
        metric_change_teachers: "! 先月から3%",
        metric_change_staff: "→ 変化なし",
        metric_change_awards: "↑ 先月から15%",
        btn_schedule_class: "授業を予約",
        btn_ai_quiz: "AIクイズ",
        btn_plan_lesson: "授業計画",
        btn_whiteboard: "ホワイトボード",
        btn_export: "エクスポート",
        btn_engagement_helper: "エンゲージメント支援",
        // Assignments & Payslips
        asg_active_title: "アクティブな課題",
        asg_active_subtitle: "課題の作成、提出の確認、クラス別の進捗を管理します。",
        btn_create_assignment: "課題を作成",
        asg_review_title: "レビュー待ち",
        btn_refresh: "更新",
        msg_loading_submissions: "提出を読み込み中...",
        msg_failed_load_submissions: "提出の読み込みに失敗しました。",
        asg_review_empty: "レビュー待ちはありません。",
        marks_entry_title: "成績入力",
        marks_select_assignment: "課題を選択",
        marks_load_submissions: "提出を読み込む",
        marks_select_prompt: "提出を表示する課題を選択してください。",
        msg_no_assignments: "課題はまだありません。",
        msg_failed_load_assignments: "課題の読み込みに失敗しました。",
        msg_assignment_requires_backend: "課題にはバックエンドが必要です。http://127.0.0.1:8000 を開いてください。",
        msg_fill_assignment_fields: "タイトル、期限、クラス（学年）を入力してください。",
        msg_create_assignment_failed: "課題の作成に失敗しました。",
        msg_create_assignment_network_error: "課題作成中のネットワークエラー。",
        msg_assignment_submit_required: "内容を入力するかリンクを追加してください。",
        msg_assignment_submit_success: "提出しました！",
        msg_assignment_submit_failed: "提出に失敗しました。",
        msg_assignment_submit_network_error: "ネットワークエラー。",
        btn_view_submissions: "提出を見る",
        label_status: "状態",
        status_submitted: "提出済み",
        label_feedback: "フィードバック",
        btn_save: "保存",
        btn_reassign: "再提出",
        asg_modal_title: "📝 新しい課題",
        label_title: "タイトル",
        label_description: "説明",
        label_class_grade: "クラス（学年）",
        label_select_grade: "学年を選択",
        label_points: "ポイント",
        label_section: "セクション",
        label_select_section_optional: "セクションを選択（任意）",
        label_due_date: "期限",
        btn_create: "作成",
        payslip_title: "給与明細",
        payslip_ytd: "年累計",
        payslip_net_pay_label: "手取り額",
        payslip_latest: "最新の支給期間",
        payslip_latest_sub: "手取り額 • Sep 2024",
        payslip_payment_method: "支払い方法",
        payslip_account_masked: "口座 •••• 2391",
        payslip_recent: "最近の明細",
        payslip_download_all: "すべてダウンロード",
        payslip_processed_paid: "処理日: Oct 01, 2024 • 状態: 支払い済み",
        payslip_view_details: "詳細を見る",
        payslip_gross: "総支給額: $5,000",
        payslip_deductions: "控除: $880",
        payslip_taxes: "税金: $620",
        payslip_print_title: "給与明細を印刷",
        payslip_generate_pdf: "給与明細PDFを生成",
        payslip_pay_period: "支給期間",
        payslip_delivery: "配信",
        payslip_download_pdf: "PDFをダウンロード",
        payslip_email_me: "メールで受け取る",
        payslip_generate_btn: "PDFを生成",
        payslip_preview: "給与明細プレビュー",
        payslip_employee_id: "社員ID: T-1024",
        payslip_processed_date: "処理日: Oct 01, 2024",
        payslip_earnings: "支給",
        payslip_base_salary: "基本給",
        payslip_allowance: "手当",
        payslip_deduction_label: "控除",
        payslip_tax: "税",
        payslip_insurance: "保険",
        pay_advance_title: "給与前払い申請",
        pay_advance_amount: "必要金額",
        pay_advance_reason: "理由",
        pay_advance_repayment: "返済方法",
        pay_advance_next_period: "次の支給期間",
        pay_advance_two_periods: "2回の支給期間",
        pay_advance_submit: "申請する",
        pay_advance_recent: "最近の申請",
        pay_advance_label: "前払い",
        pay_advance_submitted: "提出: Aug 12, 2024",
        pay_advance_pending: "保留中",
        pay_advance_approved: "承認済み",
        dashboard_live_controls: "ライブ授業コントロール",
        dashboard_now: "今",
        ph_meet_link: "Google Meet リンク",
        btn_start: "開始",
        btn_end: "終了",
        dashboard_calendar: "カレンダー",
        dashboard_upcoming_events: "今後のイベント",
        dashboard_performance_dist: "パフォーマンス分布",
        dashboard_class_avg_score: "クラス平均活動スコア",
        // Headers
        header_messages: "メッセージ",
        header_notifications: "通知",
        header_my_profile: "プロフィール",
        header_logout: "ログアウト",
        ph_search: "検索...",
        stat_active_students: "アクティブな生徒",
        nav_teachers: "教師",
        nav_students: "生徒",
        nav_schools: "学校",
        nav_resources: "リソース",
        btn_log_in: "ログイン",
        text_back: "戻る",
        login_not_a: "あなたは",
        login_switch_role: "役割を切替",
        login_student_login: "生徒ログイン",
        login_teacher_portal: "教師ポータル",
        login_parent_access: "保護者アクセス",
        login_principal_login: "校長ログイン",
        login_super_admin: "スーパー管理者",
        login_root_admin_portal: "ルート管理者ポータル",
        login_generic: "ログイン",
        role_student: "生徒",
        role_teacher: "教師",
        role_parent: "保護者",
        role_others: "その他",
        role_admin: "管理者",
        role_root_admin: "ルート管理者",
        hero_heading: "教室が\nコミュニティになる場所",
        hero_subtitle: "革新的なソリューションで教育機関を支援します",
        hero_get_started_as: "として始める...",
        feat_why_title: "なぜNoble Nexusなのか？",
        feat_main_title: "成長に必要なすべてをひとつに",
        feat_analytics_title: "スマート分析",
        feat_analytics_desc: "AIによる分かりやすい可視化で学習成果の傾向を把握できます。",
        feat_live_title: "ライブ授業",
        feat_live_desc: "統合ビデオ会議で、遠隔授業をスムーズに実施できます。",
        feat_ai_title: "AIガイダンス",
        feat_ai_desc: "一人ひとりに合った学習経路と自動フィードバックを提供します。",
        about_title: "ClassBridgeについて",
        about_main_title: "教育の未来を支える",
        about_desc: "ClassBridgeは従来の教育と最新技術のギャップを埋めるために設計されています。",
        about_teachers: "先生向け",
        about_teachers_desc: "AI出欠管理・自動採点・授業計画で日々の運用を効率化します。",
        about_students: "生徒向け",
        about_students_desc: "個別学習ルートとリアルタイム進捗で学びを加速します。",
        about_parents: "保護者向け",
        about_parents_desc: "出欠・成績・学校連絡をすばやく確認できます。",
        btn_discover_more: "詳しく見る",
        stat_engagement: "エンゲージメント率",
        stat_ai_support: "AIサポート",
        footer_company: "会社",
        footer_about: "会社概要",
        footer_press: "プレス",
        footer_careers: "採用情報",
        footer_engineering: "エンジニアリング",
        footer_accessibility: "アクセシビリティ",
        footer_resources: "リソース",
        footer_big_ideas: "ビッグアイデア",
        footer_training: "トレーニング",
        footer_remote_learning: "遠隔学習",
        footer_support: "サポート",
        footer_help_center: "ヘルプセンター",
        footer_contact: "お問い合わせ",
        footer_privacy: "プライバシーセンター",
        footer_cookies: "Cookie設定",
        footer_get_app: "アプリを入手",
        footer_terms: "利用規約",
        text_scan_visit: "スキャンしてアクセス",
        text_product_by: "Noble Nexus の製品",
        text_a_product_by: "製品提供",
        footer_noble_nexus_plus: "ノーブルネクサス プラス",
        feat_modern_title: "現代の教室のために設計",
        feat_quiz_gen: "クイズ生成",
        feat_quiz_desc: "PDFをアップロードするだけで、AIが問題と解答を即作成します。",
        link_try_generator: "生成を試す →",
        feat_student_insights: "生徒インサイト",
        feat_student_insights_desc: "成績だけでなく、支援や発展課題が必要な生徒を把握できます。",
        link_view_report: "サンプルレポートを見る →",
        feat_hybrid: "ハイブリッド教室",
        feat_hybrid_desc: "対面授業とオンライン授業をシームレスに切り替え可能。",
        link_see_how: "使い方を見る →",
        cta_ready_transform: "授業を次のレベルへ進化させませんか？",
        btn_join_free: "Noble Nexusを無料で始める"
    }
};
var currentLanguage = localStorage.getItem('appLanguage') || 'en'; // var: shared with script.js
function t(key, params = {}) {
    let text = key; // Default to key if not found
    if (translations[currentLanguage] && translations[currentLanguage][key]) {
        text = translations[currentLanguage][key];
    }
    else if (translations['en'] && translations['en'][key]) {
        text = translations['en'][key];
    }
    // Replace params
    for (const [placeholder, value] of Object.entries(params)) {
        text = text.replace(`{${placeholder}}`, value);
    }
    return text;
}
function changeLanguage(lang) {
    currentLanguage = lang;
    localStorage.setItem('appLanguage', lang);
    updateTranslations();
    document.documentElement.lang = lang; // Accessibility: Update HTML lang attribute
}
function updateTranslations() {
    // 1. Text Content
    document.querySelectorAll('[data-i18n]').forEach(el => {
        const key = el.getAttribute('data-i18n');
        if (!key)
            return;
        el.textContent = t(key);
    });
    // 2. Placeholders
    document.querySelectorAll('[data-i18n-placeholder]').forEach(el => {
        const key = el.getAttribute('data-i18n-placeholder');
        if (!key)
            return;
        el.placeholder = t(key);
    });
    // 3. Dynamic Dates
    const calDate = document.getElementById('dashboard-calendar-month');
    if (calDate) {
        const now = new Date();
        const opts = { month: 'long', year: 'numeric' };
        // Map app language codes to standard locales if necessary
        let locale = currentLanguage;
        if (locale === 'ar')
            locale = 'ar-SA';
        if (locale === 'hi')
            locale = 'hi-IN';
        if (locale === 'ja')
            locale = 'ja-JP';
        if (locale === 'es')
            locale = 'es-ES';
        if (locale === 'en')
            locale = 'en-US';
        calDate.textContent = now.toLocaleDateString(locale, opts);
    }
    // Update global selector value if called programmatically
    const globalToggle = document.getElementById('global-lang-toggle');
    if (globalToggle)
        globalToggle.value = currentLanguage;
}

function updateGlobalLanguageControlVisibility(currentViewId = null) {
    const host = document.getElementById('global-language-control');
    if (!host)
        return;
    const activeView = currentViewId || (document.querySelector('.view.active') || {}).id || '';
    const hiddenViews = ['landing-view', 'login-view', 'register-view', 'two-factor-view'];
    const shouldHide = !appState.isLoggedIn || hiddenViews.includes(activeView);
    host.style.display = shouldHide ? 'none' : 'flex';
}

function ensureGlobalLanguageControl() {
    if (document.getElementById('global-language-control'))
        return;
    const host = document.createElement('div');
    host.id = 'global-language-control';
    host.style.position = 'fixed';
    host.style.top = '16px';
    host.style.right = '20px';
    host.style.zIndex = '99999';
    host.style.background = 'rgba(255,255,255,0.95)';
    host.style.border = '1px solid #e5e7eb';
    host.style.borderRadius = '12px';
    host.style.padding = '6px 10px';
    host.style.boxShadow = '0 6px 20px rgba(15,23,42,0.12)';
    host.style.alignItems = 'center';
    host.style.gap = '8px';
    host.innerHTML = `
        <span class="material-icons" style="font-size:18px;color:#6b7280;">language</span>
        <select id="global-lang-toggle" aria-label="Global Language" style="border:0;background:transparent;outline:none;font-weight:600;color:#374151;min-width:106px;">
            <option value="en">English</option>
            <option value="es">Español</option>
            <option value="ar">العربية</option>
            <option value="hi">हिन्दी</option>
            <option value="ja">日本語</option>
        </select>
    `;
    document.body.appendChild(host);
    const sel = document.getElementById('global-lang-toggle');
    if (sel) {
        sel.value = currentLanguage;
        sel.addEventListener('change', (e) => {
            const next = e.target && e.target.value ? e.target.value : 'en';
            changeLanguage(next);
        });
    }
    updateGlobalLanguageControlVisibility();
}
// Initialize Language on Load
// Initialize Language & Auth on Load
document.addEventListener('DOMContentLoaded', () => {
    ensureGlobalLanguageControl();
    updateTranslations();
    const isLoggedIn = restoreAuthState();
    if (isLoggedIn) {
        if (appState.role === 'Student') {
            renderStudentControls();
            // Ensure views are cleared before routing logic takes over, 
            // though renderStudentControls might have already tried routing.
        }
        else if (isParentRole(appState.role)) {
            renderParentControls();
        }
        else {
            renderTeacherControls();
        }
    }
    updateGlobalLanguageControlVisibility();
    // Strict Hash-Based Routing Logic
    const hash = window.location.hash.substring(1);
    const safeSwitch = (id) => {
        // Only switch if the element exists to avoid errors
        if (document.getElementById(id)) {
            switchView(id, false);
        }
        else {
            // Fallback for invalid hash
            if (isLoggedIn) {
                if (appState.role === 'Student')
                    switchView('student-view', false);
                else if (isParentRole(appState.role))
                    switchView('parent-dashboard-view', false);
                else
                    switchView('teacher-view', false);
            }
            else {
                switchView('landing-view', false);
            }
        }
    };
    if (hash) {
        const protectedViews = ['teacher-view', 'student-view', 'parent-dashboard-view', 'roles-view', 'permissions-view'];
        // If user is NOT logged in and tries to access a protected view, redirect to landing
        if (!isLoggedIn && protectedViews.some(v => hash.startsWith(v))) {
            switchView('landing-view', false);
        }
        else {
            // Otherwise (Logged in OR Public Page), try to load the specific view from hash
            safeSwitch(hash);
        }
    }
    else {
        // No hash provided — only try role-based routing if appState is ready
        if (isLoggedIn && typeof appState !== 'undefined') {
            if (appState.role === 'Student')
                switchView('student-view', false);
            else if (isParentRole(appState.role))
                switchView('parent-dashboard-view', false);
            else
                switchView('teacher-view', false);
        }
        else {
            switchView('landing-view', false);
        }
    }
});
